---
abstract: 'An interface to SAPO''s URL shortening service'
author:
  - 'Pedro Figueiredo <me@pedrofigueiredo.org>'
build_requires:
  Test::More: 0
  XML::LibXML::XPathContext: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-PunyURL
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  Mouse: 0
  Mouse::Util::TypeConstraints: 0
  Regexp::Common: 0
  URI::Escape: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
